# Generated by Django 5.2 on 2025-11-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faild_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
