# Generated by Django 5.2.7 on 2026-01-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_faild_attempts_user_lockout_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
