# Generated by Django 5.2 on 2026-01-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_auth_session_id_user_last_otp_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_session_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_otp_sent_at',
        ),
    ]
