# Generated by Django 5.2.7 on 2026-01-20 07:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('AFN', 'Afghan Afghani'), ('USD', 'US Dollar')], default='AFN', max_length=3)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash on Delivery'), ('MOBILE_MONEY', 'Mobile Money')], default='CASH', max_length=20)),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('external_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HELD', 'Held in Escrow'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('escrow_held_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Platform commission percentage', max_digits=5)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('professional_payout', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid to professional after fees', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payment.payment')),
            ],
            options={
                'verbose_name_plural': 'Payment histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SERVICE_NOT_COMPLETED', 'Service Not Completed'), ('POOR_QUALITY', 'Poor Service Quality'), ('PROFESSIONAL_NO_SHOW', 'Professional Did Not Show Up'), ('CANCELLED_BY_PROFESSIONAL', 'Cancelled by Professional'), ('OVERCHARGED', 'Overcharged'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount to refund (can be partial)', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='payment.payment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payment_pay_transac_f578fa_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking'], name='payment_pay_booking_dc1489_idx'),
        ),
    ]
