# Generated by Django 5.2.7 on 2026-01-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='escrow_held_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='platform_fee_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='platform_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='professional_payout',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refunded_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='released_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_transaction_id',
            field=models.CharField(blank=True, default=1, help_text='Transaction ID from payment gateway (M-Paisa, etc.)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash on Delivery'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=20),
        ),
        migrations.DeleteModel(
            name='RefundRequest',
        ),
    ]
