# Generated by Django 5.2.7 on 2026-01-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_alter_professional_years_of_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service Categories'},
        ),
    ]
