# Generated by Django 5.2 on 2026-01-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pricing_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('FIXED', 'Fixed'), ('PER_UNIT', 'Per Unit')], max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.servicecategory')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='professional.professional')),
            ],
        ),
    ]
