# Generated by Django 5.2.7 on 2026-01-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_alter_professional_years_of_experience'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['professional', 'category'], name='service_ser_profess_82e6cc_idx'),
        ),
    ]
